services:
    db:
        image: mysql:latest
        container_name: mysql-container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - '3306:3306'
    app:
        build: 
            context: ..
            dockerfile: docker/Dockerfile
        container_name: express-app
        ports:
            - '3000:3000'
        depends_on:
            - db
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
